In [146]:
import snscrape.modules.twitter as sntwitter
import pandas as pd 
import itertools
from tqdm.notebook import tqdm

import nltk
from nltk.tokenize import word_tokenize
from nltk.text import Text

#import spacy

import re
import string

import matplotlib.pyplot as plt

from PIL import Image
import numpy as np

from textblob import TextBlob
from wordcloud import WordCloud, STOPWORDS

from nltk.corpus import stopwords

# Scrapping Twitter

In [72]:
import snscrape.modules.twitter as sntwitter
import pandas as pd 
import itertools
from tqdm.notebook import tqdm

loc = "-33.403713590477004, -70.73424221070437, 15km"

keyword = '(todes)'
maxTweets2 = 5000
tweets = []
tdf = None
for i,tweet in tqdm(enumerate(sntwitter.TwitterSearchScraper('todes geocode:"{}"'.format(loc)).get_items())) :
        if i > maxTweets :
            break
        username = tweet.username
        text = tweet.content
        pubdate = tweet.date
        permalink = tweet.url
        replycount = tweet.replyCount 
        retweetcount = tweet.retweetCount
        likecount = tweet.likeCount
        quotecount = tweet.quoteCount 
        tweets2.append({
            "permalink":permalink,
            "pubdate":pubdate,
            "text":text,
            "username":username,
            "retweets":retweetcount,
            "likes":likecount,
            "quotes":quotecount
        })

0it [00:00, ?it/s]

<ipython-input-72-ff1d01dbbe90>:13: FutureWarning: username is deprecated, use user.username instead
  username = tweet.username

In [56]:
todes2df = pd.DataFrame(tweets, columns=['permalink', 'pubdate', 'text', 'username', 'retweets', 'likes', 'quotes'])

In [59]:
todes2df.to_csv('todes2.csv')

In [73]:
keyword2 = '(todos)'
maxTweets2 = 187232
tweets2 = []
tdf = None
for i,tweet in tqdm(enumerate(sntwitter.TwitterSearchScraper('todos geocode:"{}"'.format(loc)).get_items())) :
        if i > maxTweets2 :
            break
        username = tweet.username
        text = tweet.content
        pubdate = tweet.date
        permalink = tweet.url
        replycount = tweet.replyCount 
        retweetcount = tweet.retweetCount
        likecount = tweet.likeCount
        quotecount = tweet.quoteCount 
        tweets2.append({
            "permalink":permalink,
            "pubdate":pubdate,
            "text":text,
            "username":username,
            "retweets":retweetcount,
            "likes":likecount,
            "quotes":quotecount
        })

0it [00:00, ?it/s]

<ipython-input-73-56f7af66d25b>:8: FutureWarning: username is deprecated, use user.username instead
  username = tweet.username

In [76]:
todos2df = pd.DataFrame(tweets2, columns=['permalink', 'pubdate', 'text', 'username', 'retweets', 'likes', 'quotes'])

In [ ]:
todos2df.to_csv('todos2.csv')

# EDA

In [250]:
todos2df.tail()

,date,time,username,text,retweets,likes,quotes,todes,permalink,pubdate
187228,2019-10-02,14:51:51,HCNworld,Felicidades a todos y mucho éxitos! #Repost @A...,1,2,0,0,https://twitter.com/HCNworld/status/1179408659...,2019-10-02 14:51:51+00:00
187229,2019-10-02,14:37:11,fdonosoc,"@jvanbiobio sea el apellido que tengas, si com...",0,0,0,0,https://twitter.com/fdonosoc/status/1179404969...,2019-10-02 14:37:11+00:00
187230,2019-10-02,14:36:02,Fac_EducacionUC,¿Por qué el rector Sánchez juega básquetbol? E...,11,24,0,0,https://twitter.com/Fac_EducacionUC/status/117...,2019-10-02 14:36:02+00:00
187231,2019-10-02,14:34:57,crisoldeoro,@carlospinourrut @Any_BS No lo sabía. Mi hija...,1,2,0,0,https://twitter.com/crisoldeoro/status/1179404...,2019-10-02 14:34:57+00:00
187232,2019-10-02,14:28:29,CICS_UDD,Ya comienza la exposicion d la Coord del #CICS...,1,2,0,0,https://twitter.com/CICS_UDD/status/1179402777...,2019-10-02 14:28:29+00:00

In [80]:
todes2df.shape

(4538, 7)

In [82]:
todos2df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187233 entries, 0 to 187232
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   permalink  187233 non-null  object
 1   pubdate    187233 non-null  datetime64[ns, UTC]
 2   text       187233 non-null  object
 3   username   187233 non-null  object
 4   retweets   187233 non-null  int64
 5   likes      187233 non-null  int64
 6   quotes     187233 non-null  int64
dtypes: datetime64[ns, UTC](1), int64(3), object(3)
memory usage: 10.0+ MB

In [83]:
todes2df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4538 entries, 0 to 4537
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   permalink  4538 non-null   object
 1   pubdate    4538 non-null   datetime64[ns, UTC]
 2   text       4538 non-null   object
 3   username   4538 non-null   object
 4   retweets   4538 non-null   int64
 5   likes      4538 non-null   int64
 6   quotes     4538 non-null   int64
dtypes: datetime64[ns, UTC](1), int64(3), object(3)
memory usage: 248.3+ KB

# Data Wrangling and Cleansing

In [85]:
todes=[]
todes += 4538 * ["1"]
todes2df["todes"]=todes

In [88]:
todes2df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4538 entries, 0 to 4537
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   permalink  4538 non-null   object
 1   pubdate    4538 non-null   datetime64[ns, UTC]
 2   text       4538 non-null   object
 3   username   4538 non-null   object
 4   retweets   4538 non-null   int64
 5   likes      4538 non-null   int64
 6   quotes     4538 non-null   int64
 7   todes      4538 non-null   object
dtypes: datetime64[ns, UTC](1), int64(3), object(4)
memory usage: 283.8+ KB

In [89]:
todes2=[]
todes2 += 187233 * ["0"]
todos2df["todes"]=todes2

In [91]:
todos2df["date"] = todos2df["pubdate"].dt.date
todos2df["time"] = todos2df["pubdate"].dt.time

In [93]:
todes2df["date"] = todes2df["pubdate"].dt.date
todes2df["time"] = todes2df["pubdate"].dt.time

In [99]:
todes2df=todes2df[['date', 'time', 'username', 'text', 'retweets', 'likes', 'quotes', 'todes', 'permalink', 'pubdate']]
todos2df=todos2df[['date', 'time', 'username', 'text', 'retweets', 'likes', 'quotes', 'todes', 'permalink', 'pubdate']]

In [252]:
#df=pd.concat([todes2df, todos2df], ignore_index=True)
#todes2df=pd.concat([todes2df, todos2df], ignore_index=True)
todes2df

,date,time,username,text,retweets,likes,quotes,todes,permalink,pubdate
0,2021-07-23,08:56:23,maltipo,"¿Porqué es tendencia un tipo machista, artero,...",0,0,0,1,https://twitter.com/maltipo/status/14184951933...,2021-07-23 08:56:23+00:00
1,2021-07-23,05:18:17,KarolCarriola,@Phoenix47941301 @ElisaLoncon @Jaime_Bassa @UE...,0,0,0,1,https://twitter.com/KarolCarriola/status/14184...,2021-07-23 05:18:17+00:00
2,2021-07-23,04:47:19,josekun0,"@bloda_d Con solo escuchar a alguien decir ""to...",0,1,0,1,https://twitter.com/josekun0/status/1418432514...,2021-07-23 04:47:19+00:00
3,2021-07-23,04:29:08,Romaure1,"@PrensaConvenci1 ""Todes"" No existe esa palabr...",0,11,0,1,https://twitter.com/Romaure1/status/1418427941...,2021-07-23 04:29:08+00:00
4,2021-07-23,04:28:28,jcff143,@isidoraMaher Siguen dando jugo jugué y juga t...,0,0,0,1,https://twitter.com/jcff143/status/14184277734...,2021-07-23 04:28:28+00:00
...,...,...,...,...,...,...,...,...,...,...
4533,2014-04-13,01:38:27,caarlosebastian,"Hasta pronto Stgo. Gracias a mis amiges, a mi ...",0,0,0,1,https://twitter.com/caarlosebastian/status/455...,2014-04-13 01:38:27+00:00
4534,2014-04-02,02:29:15,alelitz,Igual tener amigos y familia repartidos por to...,0,0,0,1,https://twitter.com/alelitz/status/45118455452...,2014-04-02 02:29:15+00:00
4535,2014-01-07,03:45:01,SpikeperezG,"""@latemporera: ¿Todes se han culiado a alguien...",0,0,0,1,https://twitter.com/SpikeperezG/status/4204006...,2014-01-07 03:45:01+00:00
4536,2013-10-11,11:48:50,diesmori,"@CONI_NONSTOP hagamos una secta? con weed, nud...",0,1,0,1,https://twitter.com/diesmori/status/3886322801...,2013-10-11 11:48:50+00:00
4537,2013-03-16,01:51:31,cotecumplido,Gracias a todes por los saludos. !!!!! Buenas ...,0,0,0,1,https://twitter.com/cotecumplido/status/312742...,2013-03-16 01:51:31+00:00

In [253]:
todes2df.drop(['pubdate'],axis = 1, inplace = True)

In [254]:
# to remove the hyperlink from the data
todes2df['text'] = df['text'].map(lambda x: re.sub(r'https?:\/\/\S+','',x))

In [255]:
# TO REMOVE THE TEXT PRESENTS AFTER @
todes2df['text'] = df['text'].map(lambda x: re.sub(r"@[A-Za-z0-9]+","", x))

In [256]:
# to remove the retweet names which pressents after _
todes2df['text'] = df['text'].map(lambda x: re.sub(r"_[A-Za-z0-9]+","", x))

In [257]:
todes2df['text'] = df['text'].map(lambda x: re.sub("[RT]","", x))

In [258]:
# getting the text into lowercase
todes2df['text'] = df['text'].str.lower()

In [259]:
# removing the speacial characters
todes2df['text'] = df['text'].map(lambda x: re.sub('\[.*?\]',' ', x))

In [261]:
# to remove the numbers
todes2df['text'] = df['text'].map(lambda x: re.sub('\w*\d\w*',' ', x))

In [262]:
# to remove empty ''""
todes2df['text'] = df['text'].map(lambda x: re.sub('[''""]',' ', x))

In [263]:
# removing '\n'
todes2df['text'] = df['text'].map(lambda x: re.sub('\n',' ', x))

In [125]:
text = '😎🚀🧑\u200d🚀☄️ ⬇️ ✊ ⏰💊🍆🤡🤷🏼😀👽🦁🌚🤣🎧🔵💻💰👌✨💸❤️📣🤣😂👊🏼⚖️🔥🚽🤘😭🩸➡️'
def remove_emoji(text):
    emoji_pattern = re.compile('[\U00010000-\U0010ffff]', flags=re.UNICODE)
    return re.sub(emoji_pattern, "",text)

In [264]:
todes2df['text'] = df['text'].apply(remove_emoji)

In [162]:
df[df['todes']=="1"]['text']

0       ¿porqué es tendencia un tipo machista  artero ...
1                       si por todes les chilenes jejejee
2        con solo escuchar a alguien decir  todes  ya ...
3         odes   no existe esa palabra cual es el afán...
4        siguen dando jugo jugué y juga todos  todas y...
                              ...
4533    hasta pronto stgo  gracias a mis amiges  a mi ...
4534    igual tener amigos y familia repartidos por to...
4535       ¿odes se han culiado a alguien de tuiter   ...
4536     hagamos una secta  con weed  nudismo y buena ...
4537    gracias a todes por los saludos        buenas ...
Name: text, Length: 4538, dtype: object

In [165]:
df['text']

0         ¿porqué es tendencia un tipo machista  artero ...
1                         si por todes les chilenes jejejee
2          con solo escuchar a alguien decir  todes  ya ...
3           odes   no existe esa palabra cual es el afán...
4          siguen dando jugo jugué y juga todos  todas y...
                                ...
191766    felicidades a todos y mucho éxitos   epost  wi...
191767     sea el apellido que tengas  si cometes un del...
191768    ¿por qué el rector sánchez juega básquetbol  e...
191769      no lo sabía   mi hija estudia esa carrera  y...
191770    ya comienza la exposicion d la coord del  cics...
Name: text, Length: 191771, dtype: object

In [168]:
df[df['todes']=='1']['tokenized_text']

0       [¿porqué, tendencia, tipo, machista, artero, s...
1                          [si, todes, chilenes, jejejee]
2       [solo, escuchar, alguien, decir, todes, merece...
3       [odes, existe, palabra, afán, escribirla, pron...
4        [siguen, dando, jugo, jugué, juga, todas, todes]
                              ...
4533    [pronto, stgo, gracias, amiges, familia, igual...
4534    [igual, tener, amigos, familia, repartidos, ch...
4535    [¿odes, culiado, alguien, tuiter, mitos, urbanos]
4536    [hagamos, secta, weed, nudismo, buena, musica,...
4537            [gracias, todes, saludos, buenas, noches]
Name: tokenized_text, Length: 4538, dtype: object

In [189]:
df.to_csv('todestodoslimpio.csv')

In [274]:
todes2df['text_without_stop'] = todes2df['tokenized_text'].apply(lambda x: [item for item in x if item not in stop_words])

In [275]:
todes2df

,date,time,username,text,retweets,likes,quotes,todes,permalink,tokenized_text,text_without_stop
0,2021-07-23,08:56:23,maltipo,¿porqué es tendencia un tipo machista artero ...,0,0,0,1,https://twitter.com/maltipo/status/14184951933...,"[¿porqué, tendencia, tipo, machista, artero, s...","[¿porqué, tendencia, tipo, machista, artero, s..."
1,2021-07-23,05:18:17,KarolCarriola,si por todes les chilenes jejejee,0,0,0,1,https://twitter.com/KarolCarriola/status/14184...,"[si, todes, chilenes, jejejee]","[si, todes, chilenes, jejejee]"
2,2021-07-23,04:47:19,josekun0,con solo escuchar a alguien decir todes ya ...,0,1,0,1,https://twitter.com/josekun0/status/1418432514...,"[solo, escuchar, alguien, decir, todes, merece...","[solo, escuchar, alguien, decir, todes, merece..."
3,2021-07-23,04:29:08,Romaure1,odes no existe esa palabra cual es el afán...,0,11,0,1,https://twitter.com/Romaure1/status/1418427941...,"[odes, existe, palabra, afán, escribirla, pron...","[odes, existe, palabra, afán, escribirla, pron..."
4,2021-07-23,04:28:28,jcff143,siguen dando jugo jugué y juga todos todas y...,0,0,0,1,https://twitter.com/jcff143/status/14184277734...,"[siguen, dando, jugo, jugué, juga, todas, todes]","[siguen, dando, jugo, jugué, juga, todas, todes]"
...,...,...,...,...,...,...,...,...,...,...,...
4533,2014-04-13,01:38:27,caarlosebastian,hasta pronto stgo gracias a mis amiges a mi ...,0,0,0,1,https://twitter.com/caarlosebastian/status/455...,"[pronto, stgo, gracias, amiges, familia, igual...","[pronto, stgo, gracias, amiges, familia, igual..."
4534,2014-04-02,02:29:15,alelitz,igual tener amigos y familia repartidos por to...,0,0,0,1,https://twitter.com/alelitz/status/45118455452...,"[igual, tener, amigos, familia, repartidos, ch...","[igual, tener, amigos, familia, repartidos, ch..."
4535,2014-01-07,03:45:01,SpikeperezG,¿odes se han culiado a alguien de tuiter ...,0,0,0,1,https://twitter.com/SpikeperezG/status/4204006...,"[¿odes, culiado, alguien, tuiter, mitos, urbanos]","[¿odes, culiado, alguien, tuiter, mitos, urbanos]"
4536,2013-10-11,11:48:50,diesmori,hagamos una secta con weed nudismo y buena ...,0,1,0,1,https://twitter.com/diesmori/status/3886322801...,"[hagamos, secta, weed, nudismo, buena, musica,...","[hagamos, secta, weed, nudismo, buena, musica,..."
4537,2013-03-16,01:51:31,cotecumplido,gracias a todes por los saludos buenas ...,0,0,0,1,https://twitter.com/cotecumplido/status/312742...,"[gracias, todes, saludos, buenas, noches]","[gracias, todes, saludos, buenas, noches]"

In [232]:
dftodesgroupby2=df.groupby(['date']).agg(['count'])

In [233]:
dftodesgroupby2

,time,username,text,retweets,likes,quotes,todes,permalink,subjectivity,polarity,analysis,tokenized_text,text_without_stop,text_nltk
,count,count,count,count,count,count,count,count,count,count,count,count,count,count
date,,,,,,,,,,,,,,
2013-03-16,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2013-10-11,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2014-01-07,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2014-04-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2014-04-13,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-19,3475,3475,3475,3475,3475,3475,3475,3475,3475,3475,3475,3475,3475,3475
2021-07-20,2619,2619,2619,2619,2619,2619,2619,2619,2619,2619,2619,2619,2619,2619
2021-07-21,3318,3318,3318,3318,3318,3318,3318,3318,3318,3318,3318,3318,3318,3318
2021-07-22,2472,2472,2472,2472,2472,2472,2472,2472,2472,2472,2472,2472,2472,2472
2021-07-23,673,673,673,673,673,673,673,673,673,673,673,673,673,673

In [242]:
dftodesgroupby['text']

            count
date
2013-03-16      1
2013-10-11      1
2014-01-07      1
2014-04-02      1
2014-04-13      1
...           ...
2021-07-19    120
2021-07-20     65
2021-07-21    133
2021-07-22     80
2021-07-23     26

[1312 rows x 1 columns]

In [214]:
df_1 = df.loc[:, ["date", "todes"]]

In [239]:
dfgb=df.groupby(['date', 'todes']).agg(['count'])

In [240]:
dfgb.to_csv('dfgb.csv')

In [ ]:
todes2df['sentiment']=todes2df['text'].apply(lambda x: TextBlob(x).sentiment.polarity)